version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"   # Mapeia a porta 80 do container para a porta 3000 da sua máquina
    restart: always
